### PR TITLE
Transcoder

### PR DESCRIPTION
**Pull request by ac-freeman**
Started implementing the Prophesee transcoder today--it's about 90% finished, I think. Can you send me some more Prophesee files to test with and work out the kinks? It would be helpful if they were longer, like 30 seconds or more.

https://github.com/arghasen10/adder-codec-rs/assets/19912588/ff445cda-cc73-4b41-b7e2-7691a929bf11

### CODE REVIEW

**Comment by arghasen10** [comment]
@ac-freeman  Sure, will mail you tomorrow.

**Comment by arghasen10** [comment]
Hi Andrew,

Happy New Year! Sorry for the late reply. Here is the link
<https://smu-my.sharepoint.com/:u:/r/personal/arghasen_smu_edu_sg/Documents/recording_231123_190244_cd.dat?csf=1&web=1&e=AXa8wQ>
to the.dat file you requested. It's quite large, so I'm here to assist in
case you encounter any challenges accessing or working with it. Should you
need any further support or have any questions, please don't hesitate to
reach out.

--
Thanks & Regards,


*Argha Sen*
*Research Scholar*
*Dept. of Computer Science & EngineeringIndian Institute of Technology
Kharagpur, India *
*https://arghasen10.github.io/ <https://arghasen10.github.io/>*
Lab Page: *https://cse.iitkgp.ac.in/resgrp/ubinet/
<https://cse.iitkgp.ac.in/resgrp/ubinet/>*

**Comment by ac-freeman** [comment]
Thanks Argha. I'm having trouble accessing the link--can you share it with `afreema4@ad.unc.edu`? My school uses a convoluted different email system for Microsoft services.

**Comment by arghasen10** [comment]
Done.
--
Thanks & Regards,


*Argha Sen*
*Research Scholar*
*Dept. of Computer Science & EngineeringIndian Institute of Technology
Kharagpur, India *
*https://arghasen10.github.io/ <https://arghasen10.github.io/>*
Lab Page: *https://cse.iitkgp.ac.in/resgrp/ubinet/
<https://cse.iitkgp.ac.in/resgrp/ubinet/>*

**Pull request merged**
